//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThayThuan_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int ID { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
        public Nullable<int> IDSanPham { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
